apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: index-app
  labels:
    app: index-app
  annotations:
    # Configuración específica para k3s/traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
  - host: northr3nd.duckdns.org
    http:
      paths:
      - path: /apps
        pathType: Prefix
        backend:
          service:
            name: index-app
            port:
              number: 80
